### PR TITLE
Support option for muting the in game music

### PR DESCRIPTION
**Pull request by dyceron**
Includes Area tracks, Metroid/Boss fights/Samus dying, item fanfares, etc

### CODE REVIEW

**Review by ThanatosGit — APPROVED** [review]
Metroid without music? What kind of madman would do such a thing?

Has some merge conflicts now because of the other merged pr.

**Comment by dyceron** [comment]
Since game patches now exists, should this go in there instead?

**Comment by dyceron** [comment]
This would make more sense as a cosmetic option. I'm not sure if that would be added to game patches or not.

**Comment by ThanatosGit** [comment]
Could move this and the map thing to a cosmetic option section.

**Pull request closed without merging**
