### PR TITLE
Add more offworld models

### PR DESCRIPTION
**Pull request by dyceron**
From left to right:
- Power Grip (AM2R)
- Speed Booster (AM2R, Dread)
- Seeker Launcher (Echoes)/Storm Missile (Dread)/Wavebuster (Prime)
- Flamethrower (Prime)
- Ice Spreader (Prime)/Sunburst (Echoes)
- Darkburst (Echoes)
- Sonic Boom (Echoes)

https://github.com/randovania/open-samus-returns-rando/assets/38679103/f089889b-228b-4b37-8a1e-1354b96e80ab

### CODE REVIEW

**Comment by dyceron** [comment]
Feel like Darkburst should be even darker, but unsure

**Comment by Miepee** [comment]
I feel like "here are recolors of a missile launcher" may not be the best accessibililty wise

**Comment by dyceron** [comment]
Well we don't exactly have the ability to make custom models

**Comment by Miepee** [comment]
Which makes me wonder if it would be better to either keep using generic offworld model for them, or to have a generic missile upgrade.

**Comment by dyceron** [comment]
I'd rather it not just be generic offworld, so I guess the latter option. Recolored missile still?

**Comment by dyceron** [comment]
Closing in favor of #391

**Pull request closed without merging**
