### PR TITLE
Remove new doors from entity groups

### PR DESCRIPTION
**Pull request by ThanatosGit**
It sucks but I run into some issues again. Wtf is wrong with adding actors to entity groups  😥

(two lines were too long according to ruff)

### CODE REVIEW

**Comment by dyceron** [comment]
What's the downside of not having these in groups? I'm also curious which doors are giving you issues.

**Comment by ThanatosGit** [comment]
I know that the game only activates entites which are part of the current active collision camera plus/minus some extra things if you just left a room / collision camera.

Adding them to no entity group makes them global and always active. It basically will consume unecessary resources.
My knowledge about engines is like zero. It maybe goes through all kind of animation loops, keeps the model in memory, keeps the hitbox active etc. but probably will not be rendered unless it is in the viewporrt.
If a beam had this range (and a player the accuracy :p) , you could maybe shoot the door from like 500 rooms away?

> I'm also curious which doors are giving you issues.

My tests in the last days took only place in 4 rooms. And 2 out of 2 doors had issues. The metroid, with the short introduction out of the water, in my metroid test vidoes, only spawns if the door at the other metroid is destroyed or if you get to the room from the right but not from the left.
The door in surface, where you put the transition to s110, can be destroyed but as soon as you enter all actors are removed in the room with the pickup and also all actors in the room you were coming from when leaving.

**Comment by dyceron** [comment]
> The metroid, with the short introduction out of the water, in my metroid test vidoes, only spawns if the door at the other metroid is destroyed or if you get to the room from the right but not from the left.
Not sure which one this is. 
> The door in surface, where you put the transition to s110, can be destroyed but as soon as you enter all actors are removed in the room with the pickup and also all actors in the room you were coming from when leaving.
Honestly for this one I'd just exclude it. It's a small puzzle room and I highly doubt we'll spawn in here anyway. Especially not from s100, only in s000. Could just keep the double for s000.

**Review by dyceron — APPROVED** [review]
I guess this will do for now. I suppose this will have to be revisited later for when we add Door Lock Rando. Hopefully not though.

**Pull request merged**
