### PR TITLE
Add option to prevent breakable blocks from respawning

### LINKED ISSUE #295: Adjust respawn timers for blocks in tunnels
All shot blocks in tunnels could just be changed to never respawn, which would help remove softlocks without bombs or pbs. Bomb blocks could also be changed but these might need to looked at in a case by case basis depending on what might be affected logically.

### PR DESCRIPTION
**Pull request by dyceron**
Excludes `weight` blocks

Fixes #295

### CODE REVIEW

**Comment by ThanatosGit** [comment]
Isn't that really bad for rooms like that? 
image

**Comment by dyceron** [comment]
Ah yeah it is. Bleh this option isn't going to be fun to have. Would need exclusions but that sounds a like a lot of work.

**Comment by dyceron** [comment]
Maybe this should be restricted to bomb blocks only?

**Comment by ThanatosGit** [comment]
It would require me to remember if there are similiar situations with bomb blocks. 🫠

It also came to my mind that this one here would be completly trivialized with the current state. Not a big fan of this option and writing down all the exclusion is really meh
image

**Comment by dyceron** [comment]
Yeah this option isn't great imo.

**Comment by dyceron** [comment]
Closing until a better solution is considered

**Pull request closed without merging**
